//nanoid is used to create random id for an array or table
import { nanoid } from 'nanoid';

export const items = [
    {
        id: nanoid(10),
        photos: '',
        title: 'iGadgitz Xtra U4457 Wind Up AM/FM Radio - Black',
        condition: 'used',
        description: `Ideal for long trips when battery capacity can be an issue,this portable AM/FM radio charges via both a hand-cranked winding mechanism and an integral solar panel. The internal long-life battery supports up to 7 hours of continuous use and can be recharged on the go by the crank or solar panel. Lightweight and portable, this radio features a telescoping antenna and 3.5mm headphone jack.`,
        category: 'sound & vision',
        brand: 'iGadgitz',
        model: 'Xtra U4457',
        color: 'black',
        year_mfd: '2020',
        price: '20.99',
        postage: 'collection',
    },
    {
        id: nanoid(10),
        title: 'Eco-Friendly Bamboo Toothbrush',
        condition: 'New',
        description:
            'The EcoBamboo Bamboo Brush is a sustainable alternative to traditional plastic toothbrushes. Made from naturally grown bamboo, this toothbrush is biodegradable and eco-friendly. The bristles are infused with activated charcoal to provide a deep clean and whiten teeth naturally.',
        category: 'Personal Care',
        brand: 'EcoBamboo',
        model: 'Bamboo Brush',
        color: 'Natural',
        year_mfd: '2024',
        price: '4.99',
        postage: 'Delivery',
    },
    {
        id: nanoid(10),
        title: 'Vintage Ceramic Vase',
        condition: 'Used',
        description:
            'This vintage ceramic vase from VintageHome is a beautiful piece of home decor. With its intricate floral design and vibrant blue color, it can add a touch of elegance to any room.',
        category: 'Home Decor',
        brand: 'VintageHome',
        model: 'Floral Vase',
        color: 'Blue',
        year_mfd: '1980',
        price: '30.00',
        postage: 'Collection',
    },
    {
        id: nanoid(10),
        title: 'Stainless Steel Kitchen Knife Set',
        condition: 'New',
        description:
            "Chef's Best Stainless Steel Kitchen Knife Set is a must-have for any home cook. The set includes a variety of knives for different culinary tasks, all made from high-quality stainless steel for durability and precision.",
        category: 'Kitchenware',
        brand: "Chef's Best",
        model: 'Knife Set',
        color: 'Silver',
        year_mfd: '2024',
        price: '50.00',
        postage: 'Delivery',
    },
    {
        id: nanoid(10),
        title: 'Handmade Woolen Blanket',
        condition: 'New',
        description:
            "Stay warm during the cold months with CozyHome's Handmade Woolen Blanket. Made from 100% pure wool, this blanket provides exceptional warmth and comfort. Its neutral grey color makes it a versatile addition to any bedroom decor.",
        category: 'Bedding',
        brand: 'CozyHome',
        model: 'Woolen Blanket',
        color: 'Grey',
        year_mfd: '2024',
        price: '70.00',
        postage: 'Delivery',
    },
    {
        id: nanoid(10),
        title: 'Indoor Air Purifying Plant',
        condition: 'New',
        description:
            "Improve your home's air quality with GreenHome's Indoor Air Purifying Plant. The Spider Plant is known for its ability to cleanse the air of pollutants, making it a great addition to any home.",
        category: 'Plants',
        brand: 'GreenHome',
        model: 'Spider Plant',
        color: 'Green',
        year_mfd: '2024',
        price: '15.00',
        postage: 'Collection',
    },
];
